require 'pry'
require './lib/dmv'
require './lib/facility'
require './lib/vehicle'
require './lib/dmv_data_service'
require './lib/registrant'
require './lib/wa_vehicle_factory'
require './lib/co_dmv_office_locations'
