require 'pry'
require './lib/registrant'
require './lib/dmv'
require './lib/facility'
require './lib/vehicle'
require './lib/dmv_data_service'
require './lib/facility'
require 'faraday'
require 'RSpec '
